public class myDemoClass{
    //TEST US-0001644
    private string a;
    public void mymethod(){
        system.debug('A1//33///');    
        a = 'a';
        if(true==true)        system.debug('A1//33///');    
    }
    public void MyBmethod(){
        system.debug('TESTPROMOTEDEPLOY');    
        a = 'a';
        if(true)
        system.debug('SCA');
    }
    public myDemoClass() {
    mymethod();
    
    }
    //
}