public class myDemoClass{
    //TEST US-0001644
    private string a;
    public void mymethod(){
        system.debug('A1//33///');    
        a = 'a';
        if(true==true)        system.debug('A1//33///');    
    }
    public void MyBmethod(){
        system.debug('TESTPROMOTEDEPLOY');    
        a = 'a';
        //JG was here
        if(true)
        system.debug('SCA');
    }
    public myDemoClass() {
    mymethod();
    
    }
    
    //JG CHange two attachment in selenium test run

    //test new user story

    //community User test
}